title: Regular Lighter +48 511 137 877
#email: not_yet@regularlighter.com
description: |
  regularlighter.com variety of lighters, tobacco and cigs. 
logo: /assets/images/logo.png
baseurl: ''
url: 'https://regularlighter.com'
paginate: 99
paginate_path: '/collectionN.:num/'
name: Regular Lighter
bio: |
  regularlighter.com variety of lighters, tobacco and cigs. 
author_image: /assets/images/author.jpg
twitter_username: regularlighter
github_username: regularlighter
analytics_id: UA-84736243-1
markdown: kramdown
permalink: '/:categories/:title/'
paypal_email: regularlighter@yahoo.com
paypal_currency: USD
kramdown:
  parse_block_html: true
sass:
  sass_dir: css
gems:
  - jekyll-paginate
  - jekyll-admin
