# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Regular Lighter 
email: your-email@domain.com
description: >
    Web Development services.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://regularlighter.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Your Name'
bio: >
    Hosting, Administration, Project Management, SEO, Web development. 
author_image: "/assets/images/author.jpg"
twitter_username: regularlighter
github_username:  regularlighter

# Google Analytics
analytics_id: "84736243"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
