title: RE G U L AR L I G H T ER&reg;
phone: 00 48 511 137 877
#email: regularlighter@yahoo.com
description: |
  regularlighter.com variety of lighters, tobacco and ciggies.
logo: /assets/images/logo.png
baseurl: ''
url: 'https://regularlighter.com'
paginate: 99
paginate_path: '/collectionN.:num/'
name: RE G U L AR L I G H T ER&reg;
bio: |
  regularlighter.com variety of lighters, tobacco and ciggies.
author_image: /assets/images/author.jpg
twitter_username: regularlighter
github_username: bartoszwais
analytics_id: UA-84736243-1
markdown: kramdown
permalink: '/:categories/:title/'
paypal_email: regularlighter@yahoo.com
paypal_currency: USD
kramdown:
  parse_block_html: true
sass:
  sass_dir: css
gems:
  - jekyll-paginate
  - jekyll-admin
